/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package question4;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.net.ServerSocket;
import java.net.Socket;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Scanner;


/**
 *
 * @author Gogohaya
 */
public class ex4_server extends javax.swing.JFrame {

    /**
     * Creates new form ex4_server
     */
    
    static ServerSocket ss;
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    
    public ex4_server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text_area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_area2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        text_area.setEditable(false);
        text_area.setColumns(20);
        text_area.setRows(5);
        jScrollPane1.setViewportView(text_area);

        text_area2.setEditable(false);
        text_area2.setColumns(20);
        text_area2.setRows(5);
        jScrollPane2.setViewportView(text_area2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ex4_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ex4_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ex4_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ex4_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ex4_server().setVisible(true);
            }
        });
        
        int currentPlace = 0;
        
        try{
            ss = new ServerSocket(1201);
            s = ss.accept();
            text_area.setText("");
            din = new DataInputStream(s.getInputStream());
            dout  = new DataOutputStream(s.getOutputStream());
            
            String msgin = "";
            
            
            
            int i =0;
            while(!msgin.equals("exit")){
                
                msgin = din.readUTF();
                
                if(msgin.equals("first")){
                    
                   currentPlace = 0;
                   
                   //------------------------------------First----------------------------------------
                   try {
                    //Reader to read old data
                    File myObj = new File("file.txt");
                    Scanner myReader = new Scanner(myObj);
                    String data = "";
                    
                    
                    
                    while (myReader.hasNextLine()) {
                      data = data.concat(myReader.nextLine()+"\n");
                      i++;
                    }
                    
                    text_area2.setText(data);
                    String[] fileData = data.split("\n");
                   
                    String msgout = fileData[0];

                    dout.writeUTF(msgout);
                    myReader.close();
                  } catch (IOException e) {
                    System.out.println("An error occurred.");
                    e.printStackTrace();
                  }	

                

                   
                   
                          
                //------------------------------------endFirst----------------------------------------                
                                
                }else if(msgin.equals("next")){
                   currentPlace ++;
                   
                                          try {
                    //Reader to read old data
                    File myObj = new File("file.txt");
                    Scanner myReader = new Scanner(myObj);
                    String data = "";
                    
                    
                    
                    while (myReader.hasNextLine()) {
                      data = data.concat(myReader.nextLine()+"\n");
                      i++;
                    }
                    
                    text_area2.setText(data);
                    String[] fileData = data.split("\n");
                   
                    String msgout = fileData[currentPlace];

                    dout.writeUTF(msgout);
                   
                    
                    myReader.close();
                  } catch (IOException e) {
                    System.out.println("An error occurred.");
                    e.printStackTrace();
                  }
                                          
                                          
                }else if(msgin.equals("previous")){
                   currentPlace --;
                   
                                          try {
                    //Reader to read old data
                    File myObj = new File("file.txt");
                    Scanner myReader = new Scanner(myObj);
                    String data = "";
                    
                    
                    
                    while (myReader.hasNextLine()) {
                      data = data.concat(myReader.nextLine()+"\n");
                      i++;
                    }
                    
                    text_area2.setText(data);
                    String[] fileData = data.split("\n");
                   
                    String msgout = fileData[currentPlace];

                    dout.writeUTF(msgout);
                   
                    
                    myReader.close();
                  } catch (IOException e) {
                    System.out.println("An error occurred.");
                    e.printStackTrace();
                  }
                                          
                                          
                }else if(msgin.equals("last")){
                    
                       try {
                    //Reader to read old data
                    File myObj = new File("file.txt");
                    Scanner myReader = new Scanner(myObj);
                    String data = "";
                    
                    
                    
                    while (myReader.hasNextLine()) {
                      data = data.concat(myReader.nextLine()+"\n");
                      i++;
                    }
                    
                    text_area2.setText(data);
                    String[] fileData = data.split("\n");
                   
                    String msgout = fileData[i-1];

                    dout.writeUTF(msgout);
                   
                    
                    myReader.close();
                  } catch (IOException e) {
                    System.out.println("An error occurred.");
                    e.printStackTrace();
                  }
                   
                   
                   
                   currentPlace = i-1;
                   
                }else{
                    
                String[] splited = msgin.split("--");
		String name = splited[0];
		String street = splited[1]; 
		String city = splited[2];
                String state = splited[3];
                String zip = splited[4];
                
                
                text_area.setText(text_area.getText().trim()+"\n Name: "+name);
                text_area.setText(text_area.getText().trim()+"\n Street: "+street);
                text_area.setText(text_area.getText().trim()+"\n City: "+city);
                text_area.setText(text_area.getText().trim()+"\n State: "+state);
		text_area.setText(text_area.getText().trim()+"\n Zip: "+zip);
		try {
                    //Reader to read old data
                    File myObj = new File("file.txt");
                    Scanner myReader = new Scanner(myObj);
                    String data = "";
                    
                    
                    
                    while (myReader.hasNextLine()) {
                      data = data.concat(myReader.nextLine()+"\n");
                      i++;
                    }
                    
                    text_area2.setText(data);
                    String[] fileData = data.split("\n");
                    //writer to write on it
                    FileWriter myWriter = new FileWriter("file.txt");
                    
                   //String oldData = text_area2.getText().trim();
                    data = data+"Name: "+name+" Street: "+street+" City: "+city+" State: "+state+" Zip: "+zip;
                    myWriter.write(data);
                    myWriter.close();
                    text_area.setText(text_area.getText().trim()+"\n\t\t Successfully wrote to the file :))");
                    
                    myReader.close();
                  } catch (IOException e) {
                    System.out.println("An error occurred.");
                    e.printStackTrace();
                  }	

                
                String msgout = "Done Added";

                dout.writeUTF(msgout);
                
                
            }
            
            
            
            }   
        }catch(Exception e){
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea text_area;
    private static javax.swing.JTextArea text_area2;
    // End of variables declaration//GEN-END:variables
}
